plugin:
    name: 'romainmazb.femodeleditor::lang.plugin.name'
    description: 'romainmazb.femodeleditor::lang.plugin.description'
    author: RomainMazB
    icon: oc-icon-cubes
    homepage: 'https://www.octobercms.fr'
navigation:
    main-menu:
        label: 'romainmazb.femodeleditor::lang.menus.main-menu'
        url: romainmazb/femodeleditor/fememodels
        icon: icon-cubes
