plugin:
    name: 'romainmazb.femodeleditor::lang.plugin.name'
    description: 'romainmazb.femodeleditor::lang.plugin.description'
    author: RomainMazB
    icon: oc-icon-cubes
    homepage: 'https://www.octobercms.fr'
permissions:
    manage_feme:
        tab: 'romainmazb.femodeleditor::lang.plugin.name'
        label: 'romainmazb.femodeleditor::lang.permission'
