list: $/romainmazb/femodeleditor/models/fememodel/columns.yaml
modelClass: RomainMazB\FEModelEditor\Models\FEMEModel
title: FEMEModels
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'romainmazb/femodeleditor/fememodels/update/:id'
